add wave -position insertpoint sim:/processor/*
add wave -position insertpoint sim:/alu/*
force -freeze sim:/processor/reset 0 0
force -freeze sim:/processor/MDRin 0 0
force -freeze sim:/processor/DSTin 0 0
force -freeze sim:/processor/SRCin_a 0 0
force -freeze sim:/processor/INC_A 0 0
force -freeze sim:/processor/DEC_A U 0
force -freeze sim:/processor/ADD_AB 0 0
force -freeze sim:/processor/R0out 0 0
force -freeze sim:/processor/R1out 0 0
force -freeze sim:/processor/R2out 0 0
force -freeze sim:/processor/R3out 0 0
force -freeze sim:/processor/R4out 0 0
force -freeze sim:/processor/DEC_A 0 0
force -freeze sim:/processor/R5out 0 0
force -freeze sim:/processor/R6out 0 0
force -freeze sim:/processor/R7out 0 0
force -freeze sim:/processor/WR 0 0
force -freeze sim:/processor/Zin 0 0
force -freeze sim:/processor/IRin 0 0
force -freeze sim:/processor/MARin_B 0 0
force -freeze sim:/processor/SRCin_a_or_b 0 0
force -freeze sim:/processor/MARin_A_or_B 0 0
force -freeze sim:/processor/MDRin_or_RD 0 0
force -freeze sim:/processor/MPC 11111 0
force -freeze sim:/alu/OutFlag 16#0 0